QDRANT_URL = "https://b3962249-e1f0-4625-b512-8adbf6e4cd60.sa-east-1-0.aws.cloud.qdrant.io:6333"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6MDM0YTQ2MTQtNGYyZC00ZDZhLWFhZDAtZDI5ODEyZGY1ZTdjIn0.F5B4goKuhonMW51N-lzVFckKg9NthVbrVoucarCpj1w"
QDRANT_COLLECTION = os.environ.get("QDRANT_COLLECTION", "bni_training")
HF_TOKEN = "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"

google_api_key = "AIzaSyBGdrsEhrZT4CfVsXmLL9QW-SUYSPt0wKQ" or os.environ["GOOGLE_API_KEY"]
qdrant_url = "b3962249-e1f0-4625-b512-8adbf6e4cd60.sa-east-1-0.aws.cloud.qdrant.io"
qdrant_api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6MDM0YTQ2MTQtNGYyZC00ZDZhLWFhZDAtZDI5ODEyZGY1ZTdjIn0.F5B4goKuhonMW51N-lzVFckKg9NthVbrVoucarCpj1w"

NGROK_AUTHTOKEN = "3IR9xBv8ZQtvxZPioW0bu1wgRoj_7x2mFEsktBaXmpME3jrXG"